---
driver:
  name: docker

driver_config:
  sudo: false
  use_sudo: false
  require_chef_omnibus: 11.16.4
  image: oracle/oel67:1.0
  http_proxy: http://den00bjg.us.oracle.com:8124
  https_proxy: http://den00bjg.us.oracle.com:8124

provisioner:
  name: chef_zero
  use_sudo: false
  client_rb:
    http_proxy: http://den00bjg.us.oracle.com:8124
    https_proxy: http://den00bjg.us.oracle.com:8124
    no_proxy: localhost,127.0.0.1

platforms:
- name: oel
  driver_config:
    sudo: false
    use_sudo: false
    require_chef_omnibus: 11.16.4
    image: oracle/oel67:1.0
    platform: rhel
    hostname: default-oel65-chef-java
    forward:
      - 9200:9200

suites:
  - name: default
    driver:
      vm_hostname: default-oel65-chef-java
    data_bags_path: "test/integration/data_bags"
    run_list:
      - recipe[omc_elasticsearch_test::default]
      - recipe[test-helper::default]
    attributes:
      java:
         install_flavor: 'oracle'
         jdk_version: '8'
         oracle:
           accept_oracle_download_terms: true
      omc_elasticsearch:
            home: '/opt/elasticsearch_home'
            version: '1.7.1-1'
            base_url: 'http://packages.elasticsearch.org/elasticsearch/1.7/centos'
            gpgkey_url: 'https://packages.elasticsearch.org/GPG-KEY-elasticsearch'
            cluster_name: 'omc-eventstore-localdev'
            install_path: '/usr/share/elasticsearch'
            data_path: '/data/omc-eventstore-localdev/data'
            log_path: '/data/omc-eventstore-localdev/log'
            work_path: '/data/omc-eventstore-localdev/work'
            config_path: '/etc/elasticsearch'
            pid_path: '/var/run/elasticsearch'
            transport_port: 9300
            http_port: 9200
            publish_ip: '0.0.0.0'
            bind_ip: '0.0.0.0'
            elasticsearch_data_bag_info:
               slapchop: 'elasticsearch_localdev'
            override_java_opts:
                 -Xmx: '799m'
                 -Xms: '600m'
                 -Xss: '256k'
            override_sysconfig: { ES_RESTART_ON_UPGRADE: false }
            override_config: {}
