driver:
  name: vagrant

provisioner:
  name: chef_zero
  environments_path: "test/integration/environments"
  roles_path: "test/integration/roles"
  data_bags_path: "test/integration/data_bags"
  encrypted_data_bag_secret_key_path: "test/integration/default/encrypted_data_bag_secret"
  client_rb:
     environment: localdev

platforms:
  - name: chef11
    driver:
      vm_hostname: default-oel65-chef-java
      box: oel65-chef-java
    provisioner:
      require_chef_omnibus: 11.16.4
  - name: chef12
    driver:
      vm_hostname: default-oel65-chef-java
      box: oel65-chef-java
      network:
        - ["forwarded_port", {guest: 9200, host: 29202}]
    provisioner:
      require_chef_omnibus: 12.12.15

suites:
  - name: default
    run_list:
      - recipe[omc_elasticsearch_test::default]
    attributes:
