driver:
  name: vagrant
  customize:
    memory: 2048

provisioner:
  name: chef_zero
  #require_chef_omnibus: 11.16.4
  #http_proxy: http://www-proxy.us.oracle.com:80
  #https_proxy: http://www-proxy.us.oracle.com:80

platforms:
  - name: oel65-chef-java

suites:
  - name: default
    run_list:
      - recipe[omc_elasticsearch::default]
    attributes:
      java:
         install_flavor: 'oracle'
         jdk_version: '8'
         oracle:
           accept_oracle_download_terms: true

